spring:
  application:
    name: study-native-image-with-springboot3-application

logging:
  file:
    name: ${spring.application.name}.log

test.bean.enabled: true
test.bean.type: A

filterOrder: 1
filter-order: 2