server:
  port: 8081

spring:
  application:
    name: test-compatibility-springboot3-seata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

seata:
  tx-service-group: my_group
  service:
    vgroup-mapping:
      my_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: file
    nacos:
      server-addr: 192.168.1.103:8848
    eureka:
      service-url: http://192.168.1.103:8761/eureka
  config:
    type: file
    nacos:
      server-addr: 192.168.1.103:8848

logging:
  file:
    path: .\logs\
    name: ${spring.application.name}.log

