server:
  port: 8081

spring:
  application:
    name: test-seata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

seata:
  tx-service-group: my_group
  service:
    vgroup-mapping:
      my_group: default
    grouplist:
      default: 127.0.0.1:8091
